/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileCreateRouteImport } from './routes/profile/create'
import { Route as ProfileIdRouteImport } from './routes/profile/$id'
import { Route as MeRequestsRouteImport } from './routes/me/requests'
import { Route as MeFavoritesRouteImport } from './routes/me/favorites'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCreateRoute = ProfileCreateRouteImport.update({
  id: '/profile/create',
  path: '/profile/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRequestsRoute = MeRequestsRouteImport.update({
  id: '/me/requests',
  path: '/me/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const MeFavoritesRoute = MeFavoritesRouteImport.update({
  id: '/me/favorites',
  path: '/me/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/me/favorites': typeof MeFavoritesRoute
  '/me/requests': typeof MeRequestsRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/create': typeof ProfileCreateRoute
  '/profile/edit': typeof ProfileEditRoute
  '/me/': typeof MeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/me/favorites': typeof MeFavoritesRoute
  '/me/requests': typeof MeRequestsRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/create': typeof ProfileCreateRoute
  '/profile/edit': typeof ProfileEditRoute
  '/me': typeof MeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/me/favorites': typeof MeFavoritesRoute
  '/me/requests': typeof MeRequestsRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/create': typeof ProfileCreateRoute
  '/profile/edit': typeof ProfileEditRoute
  '/me/': typeof MeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/discover'
    | '/login'
    | '/register'
    | '/auth/callback'
    | '/me/favorites'
    | '/me/requests'
    | '/profile/$id'
    | '/profile/create'
    | '/profile/edit'
    | '/me/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/discover'
    | '/login'
    | '/register'
    | '/auth/callback'
    | '/me/favorites'
    | '/me/requests'
    | '/profile/$id'
    | '/profile/create'
    | '/profile/edit'
    | '/me'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/discover'
    | '/login'
    | '/register'
    | '/auth/callback'
    | '/me/favorites'
    | '/me/requests'
    | '/profile/$id'
    | '/profile/create'
    | '/profile/edit'
    | '/me/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  MeFavoritesRoute: typeof MeFavoritesRoute
  MeRequestsRoute: typeof MeRequestsRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ProfileCreateRoute: typeof ProfileCreateRoute
  ProfileEditRoute: typeof ProfileEditRoute
  MeIndexRoute: typeof MeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/create': {
      id: '/profile/create'
      path: '/profile/create'
      fullPath: '/profile/create'
      preLoaderRoute: typeof ProfileCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/requests': {
      id: '/me/requests'
      path: '/me/requests'
      fullPath: '/me/requests'
      preLoaderRoute: typeof MeRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/favorites': {
      id: '/me/favorites'
      path: '/me/favorites'
      fullPath: '/me/favorites'
      preLoaderRoute: typeof MeFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  MeFavoritesRoute: MeFavoritesRoute,
  MeRequestsRoute: MeRequestsRoute,
  ProfileIdRoute: ProfileIdRoute,
  ProfileCreateRoute: ProfileCreateRoute,
  ProfileEditRoute: ProfileEditRoute,
  MeIndexRoute: MeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
